Feature/ufs 268 dashboard screen
ukriorg/ukripoc-application pull request #3
Opened 2019-06-11 13:57 UTC by aerian-darren

Using mocked data for now

2019-06-11 13:58 UTC, aerian-darren commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +                    props.applications.map((application: any) => {
Changing....

2019-06-11 15:10 UTC, aerian-darren commented
This is using a mocked response for now

2019-06-13 09:23 UTC, ascorbic requested changes

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.test.tsx
> +            .create(<ApplicationDashboard applications={() => ""} />)
What's going on here?

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +    function daysLeft(date: string | null) {
Extract this outside the component into a helper that generates the time and suffix (returning the strings, not the JSX. You could do this as an array which you imemdiately destructure). A general rule is to not define functions inside the component unless they need access to hook data. This

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +        const closeDateTime = closeDate.getTime();
Check that date has been successfully created

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +    function friendlyDate(date: string | null) {
Extract this too

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +                <span>In progress ({applications && applications.length})</span>
Change to `{applications ? applications.length : 0 }` or you'll end up with nulls.

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +                        if (!application) {
Don't return loading here. Just return null.

2019-06-13 09:23 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +                                            <div>
Why are you using a div here?

2019-06-13 12:00 UTC, ascorbic requested changes

2019-06-13 12:00 UTC, ascorbic commented on src/lib/dateandtime.ts
> +    const result = { time: timeToShow, prefix: prefixToShow };
No need to assign to a variable. Just return it.

2019-06-13 12:00 UTC, ascorbic commented on src/lib/dateandtime.ts
> +export function daysLeft(date: string | null) {
Make these arrow functions

2019-06-13 12:00 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +function showDaysLeft(closeDate: string | null) {
This doesn't need to be a function now

2019-06-13 12:00 UTC, ascorbic commented on src/lib/dateandtime.ts
> +    const result = { time: timeToShow, prefix: prefixToShow };
return [timetoShow, prefixToShow];

2019-06-13 12:00 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +interface Typed {
Don't do this here. Type the helper function's return.

2019-06-13 13:13 UTC, ascorbic requested changes

2019-06-13 13:13 UTC, ascorbic commented on src/types.d.ts
> +
This isn't needed

2019-06-13 13:13 UTC, ascorbic commented on src/components/ApplicationDashboard/ApplicationDashboard.tsx
> +                        const result: DateandtimeReturnType = {
You don't need to spread or type this. You can either just use the result:

`const result = daysLeft(application.closeDate)`

 which is identical to the result you have, or deconstruct it:

`const { timeToShow, prefixToShow } = daysLeft(application.closeDate);`

2019-06-13 14:51 UTC, ascorbic commented on src/lib/dateandtime.ts
> +    let prefixToShow = "Hours";
Not going to reject the PR for this, but it's a suffix, not a prefix!

2019-06-13 14:51 UTC, ascorbic approved these changes

2019-06-13 14:52 UTC, ascorbic commented on src/lib/dateandtime.ts
> +    let prefixToShow = "Hours";
Probably doesn't need the "toShow" bit either.

2019-06-13 15:13 UTC, merged