initial commit for application page
ukriorg/ukripoc-application pull request #4
Opened 2019-06-12 14:43 UTC by aerian-darren

Still using mocked data, types are in place though

2019-06-12 14:44 UTC, aerian-darren commented on src/components/Application/Application.tsx
> +                                                : "incomplete"}
capitalise and add icon

2019-06-14 09:10 UTC, ascorbic requested changes

2019-06-14 09:10 UTC, ascorbic commented on src/components/Application/Application.test.tsx
> +            .create(<Application application={() => ""} />)
??

2019-06-14 09:10 UTC, ascorbic commented on src/components/Application/Application.tsx
> +                                <strong>Application number:</strong>
You know this is wrong! Use the govuk components.

2019-06-14 09:10 UTC, ascorbic commented on src/components/ApplicationPage/ApplicationPage.tsx
> +const v: GetFundingApplicationQuery = {
There's no reason to use mock data in the live page. Mock it in the storybook to check designs, and use live data in the real site.

2019-06-14 09:10 UTC, ascorbic commented on src/components/AuthWrapper/AuthWrapper.tsx
> +                <ApplicationPage path="/application/:id" />
This doesn't belong here. This component is for wrapping all the authentication stuff.

2019-06-14 11:07 UTC, aerian-darren commented
@ascorbic the last commit fixes the issue I had with the AuthWrapper Component forcing the redirect. I believe these are all the points mentioned above covered.

2019-06-17 08:46 UTC, ascorbic approved these changes

2019-06-17 08:47 UTC, merged